[metadata]
name = aiidalab-dlpoly
version = 0.0.1
author = Dr. Benjamin T. Speake
description = AiiDAlab application for running and managing DL_POLY molecular dynamics simulations.
long_description = file: README.md
long_description_content_type = text/markdown
license = BSD-3-Clause
classifiers =
    Development Status :: 3 - Alpha
    License :: OSI Approved :: BSD License
    Programming Language :: Python :: 3

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
install_requires =
    aiida-core>=2.0,<3
    aiidalab>=23.0
    aiidalab-widgets-base>=2.0
    alc-aiidalab-widgets>=0.1.0
    ipywidgets

[options.packages.find]
where = src

[options.extras_require]
dev =
    pytest>=8.0
    pytest-cov>=6.0
    ruff>=0.11.0
docs =
    sphinx>=8.0
    piccolo-theme>=0.14.0
    sphinx-toolbox

[tool:pytest]
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning

[aiidalab]
title = AiiDAlab DL_POLY
categories =
    quantum
logo = images/DL_Software_logo.png
